ServerEvents.recipes(sog => {

    sog.recipes.gtceu.fusion_reactor('cosmic_titanium')
            .inputFluids('gtceu:titanium 350', 'gtceu:resonant_essence 16')
            .outputFluids('gtceu:cosmic_titanium 32')
            .fusionStartEU(640000000)
            .EUt((GTValues.VA[GTValues.UEV]))
            .totalCWU(64*500)
            .CWUt(64)
    sog.recipes.gtceu.fusion_reactor('cosmic_tungsten')
            .inputFluids('gtceu:tungsten 350', 'gtceu:resonant_essence 16')
            .outputFluids('gtceu:cosmic_tungsten 32')
            .fusionStartEU(640000000)
            .EUt((GTValues.VA[GTValues.UEV]))
            .totalCWU(64*500)
            .CWUt(64)
    sog.recipes.gtceu.fusion_reactor('cosmic_iridium')
            .inputFluids('gtceu:stabilized_iridium 350', 'gtceu:resonant_essence 16')
            .outputFluids('gtceu:cosmic_iridium 32')
            .fusionStartEU(640000000)
            .EUt((GTValues.VA[GTValues.UEV]))
            .totalCWU(64*500)
            .CWUt(96)
    sog.recipes.gtceu.fusion_reactor('cosmic_osmium')
            .inputFluids('gtceu:osmium 355', 'gtceu:resonant_essence 16')
            .outputFluids('gtceu:cosmic_osmium 32')
            .fusionStartEU(640000000)
            .EUt((GTValues.VA[GTValues.UEV]))
            .totalCWU(64*500)
            .CWUt(64)
    sog.recipes.gtceu.fusion_reactor('nihonium')
            .inputFluids('gtceu:zinc 255', 'gtceu:bismuth 120')
            .outputFluids('gtceu:nihonium 32')
            .fusionStartEU(640000000)
            .EUt((GTValues.VA[GTValues.UEV]))
            .totalCWU(256*500)
            .CWUt(256)
    sog.recipes.gtceu.fusion_reactor('oganesson')
            .inputFluids('gtceu:californium 255', 'gtceu:cosmic_iridium 35')
            .outputFluids('gtceu:oganesson 32')
            .fusionStartEU(640000000)
            .EUt((GTValues.VA[GTValues.UEV]))
            .totalCWU(256*500)
            .CWUt(256)


})